/**
 * Observer — extracts structured observations from conversation history.
 *
 * Based on Mastra's Observational Memory system.
 * https://mastra.ai/blog/observational-memory
 */

import OpenAI from 'openai'
import type { Message } from '../types.js'
import { isTextMessage, isFunctionCall, isFunctionCallOutput } from '../types.js'
import { estimateTokens } from '../tokens.js'
import { extractTag } from './xml.js'

const MAX_SECTION_CHARS = 6_000
const MAX_TOOL_PAYLOAD_CHARS = 3_000
const OBSERVER_MAX_OUTPUT_TOKENS = 8_000

export interface ObserverResult {
  observations: string
  currentTask?: string
  suggestedResponse?: string
  raw: string
}

const truncate = (text: string, limit: number): string =>
  text.length <= limit ? text : `${text.slice(0, limit - 3)}...`

export const serializeMessages = (messages: Message[]): string =>
  messages
    .map((msg, i) => {
      if (isFunctionCallOutput(msg)) {
        return `**Tool Result (#${i + 1}):**\n${truncate(msg.output, MAX_TOOL_PAYLOAD_CHARS)}`
      }

      if (isFunctionCall(msg)) {
        return `**Assistant Tool Call (#${i + 1}):**\n[Tool: ${msg.name}] ${truncate(msg.arguments, MAX_TOOL_PAYLOAD_CHARS)}`
      }

      if (isTextMessage(msg)) {
        const label = msg.role.charAt(0).toUpperCase() + msg.role.slice(1)
        const content = typeof msg.content === 'string' ? msg.content : ''
        return `**${label} (#${i + 1}):**\n${truncate(content, MAX_SECTION_CHARS) || '[empty]'}`
      }

      return ''
    })
    .filter(Boolean)
    .join('\n\n---\n\n')

const SYSTEM_PROMPT = `You are the memory consciousness of an AI assistant.
Your observations will be the ONLY information the assistant has about past interactions.

Extract high-fidelity observations from conversation history.
Do not chat. Do not explain. Output only structured XML.

Rules:
1) Every observation MUST be tagged with its source: [user], [assistant], or [tool:name].
   - [user]: facts, preferences, decisions explicitly stated by the user.
   - [assistant]: actions taken, commitments made, or content generated by the assistant.
   - [tool:name]: outcomes of tool calls (e.g. [tool:write_file], [tool:read_file]).
2) Priority markers:
   - 🔴 high: explicit user facts, preferences, decisions, completed goals.
   - 🟡 medium: active work, project details, tool outcomes, unresolved blockers.
   - 🟢 low: tentative or minor details, assistant elaborations.
3) Preserve concrete details: names, numbers, dates, file paths, quoted phrasing.
4) Capture state changes explicitly ("updating previous preference").
5) Keep observations concise but information-dense.
6) Do NOT repeat observations that already exist in previous observations.

Output format (strict):
<observations>
* 🔴 [user] ...
* 🟡 [assistant] ...
* 🟡 [tool:write_file] ...
</observations>

<current-task>
Primary: ...
</current-task>

<suggested-response>
...
</suggested-response>`.trim()

const buildPrompt = (previousObservations: string, messageHistory: string): string =>
  [
    '## Previous Observations',
    '',
    previousObservations || '[none]',
    '',
    '---',
    '',
    'Do not repeat these existing observations. Only extract new ones.',
    '',
    '## New Message History',
    '',
    messageHistory || '[none]',
    '',
    '---',
    '',
    'Extract new observations. Return only XML with <observations>, <current-task>, <suggested-response>.',
  ].join('\n')

export const parseObserverOutput = (raw: string): ObserverResult => ({
  observations: extractTag(raw, 'observations') ?? raw.trim(),
  currentTask: extractTag(raw, 'current-task'),
  suggestedResponse: extractTag(raw, 'suggested-response'),
  raw,
})

export const runObserver = async (
  openai: OpenAI,
  model: string,
  previousObservations: string,
  messages: Message[],
): Promise<ObserverResult> => {
  const history = serializeMessages(messages)
  if (!history.trim()) {
    return { observations: '', raw: '' }
  }

  console.log(`  [observer] Extracting from ${messages.length} messages (~${estimateTokens(history)} tokens)`)

  const response = await openai.responses.create({
    model,
    instructions: SYSTEM_PROMPT,
    input: buildPrompt(previousObservations, history),
    temperature: 0.3,
    max_output_tokens: OBSERVER_MAX_OUTPUT_TOKENS,
    store: false,
  })

  const raw = response.output_text ?? ''
  const result = parseObserverOutput(raw)
  const lineCount = result.observations.split('\n').filter((l) => l.trim()).length

  console.log(`  [observer] Extracted ${lineCount} observation lines (~${estimateTokens(result.observations)} tokens)`)

  return result
}
